[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./deployments/" }]

[rpc_endpoints]
monad_testnet = "${MONAD_RPC_URL}"

[etherscan]
monad_testnet = { key = "${MONAD_EXPLORER_API_KEY}", url = "https://explorer.testnet.monad.xyz/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
